#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x5_3(LCTL_T(KC_Q), KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_TAB, LSFT_T(KC_Z), KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_LALT, KC_DQUO, LCTL_T(KC_QUOT), LM(1,MOD_LGUI), KC_SPC, LT(5,KC_ESC), MO(2), LT(2,KC_BSPC), MO(3)),

    [1] = LAYOUT_split_3x5_3(KC_Q, KC_1, KC_2, KC_3, KC_GRV, KC_K, LSFT_T(KC_1), LSFT(KC_2), LSFT(KC_3), KC_S, KC_A, KC_4, KC_5, KC_6, KC_H, KC_H, KC_J, KC_K, KC_L, KC_F, KC_Z, KC_SPC, KC_C, LSFT(KC_E), KC_B, KC_J, KC_T, KC_M, LALT(KC_R), KC_D, KC_TRNS, KC_NO, KC_LGUI,KC_O, KC_LSFT, KC_RALT),

	[2] = LAYOUT_split_3x5_3(KC_TILD, KC_EXLM, KC_AMPR, KC_HASH, KC_MINS, KC_LBRC, KC_LCBR, KC_RCBR, KC_LPRN, KC_RPRN, KC_GRV, KC_DLR, KC_COMM, KC_DOT, KC_COLN, KC_LEFT, KC_DOWN, KC_UP, KC_RIGHT, KC_PERC, KC_PLUS, KC_PIPE, KC_SLSH, KC_CIRC, KC_UNDS, KC_RBRC, KC_EQL, KC_BSLS, KC_AT, KC_ASTR, KC_LSFT, KC_ENTER, KC_SCLN, KC_TRNS, KC_ENT, DF(6)),
	[3] = LAYOUT_split_3x5_3(KC_PAST, KC_1, KC_2, KC_3, KC_0, KC_WH_U, KC_F1, KC_F2, KC_F3, KC_F11, KC_PSLS, KC_4, KC_5, KC_6, KC_PPLS, KC_F10, KC_F4, KC_F5, KC_F6, KC_END, KC_MINS, KC_7, KC_8, KC_9, KC_EQL, KC_WH_D, KC_F7, KC_F8, KC_F9, KC_F12, KC_LGUI, KC_SPC, KC_F13, KC_TRNS, KC_ENT, KC_TRNS),

	[4] = LAYOUT_split_3x5_3(KC_TILD, KC_EXLM, KC_AMPR, KC_HASH, KC_MINS, KC_UP, KC_LCBR, KC_RCBR, KC_LPRN, KC_RPRN, KC_GRV, KC_DLR, KC_COMM, KC_DOT, KC_LEFT, KC_RGHT, KC_LBRC, KC_RBRC, KC_CIRC, KC_PERC, KC_PLUS, KC_PIPE, KC_SLSH, KC_COLN, KC_UNDS, KC_DOWN, KC_EQL, KC_BSLS, KC_AT, KC_ASTR, KC_LSFT, KC_ENTER, KC_SCLN, KC_TRNS, KC_ENT, KC_TRNS),

	[5] = LAYOUT_split_3x5_3(LSFT(KC_Q), KC_NO, KC_NO, KC_NO, LSFT(KC_V), KC_NO, KC_NO, KC_NO, KC_NO, LSFT(KC_A), KC_NO, KC_NO, KC_NO, KC_NO, LCTL(LSFT(KC_D)), KC_H, KC_J, KC_K, KC_L, KC_NO, LSFT(KC_Z), KC_NO, KC_NO, KC_NO,LSFT(KC_V), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LGUI, KC_NO, KC_NO, KC_NO),

    [6] = LAYOUT_split_3x5_3(
        KC_TAB,   KC_Q,   KC_W,    KC_E,    KC_R,           KC_NO,  KC_NO, KC_UP,   KC_NO,  KC_TAB,
        KC_LSFT,  KC_A,   KC_S,    KC_D,    KC_F,           KC_NO,  KC_LEFT, KC_DOWN, KC_RGHT,  KC_RSFT,
        KC_LCTL,  KC_Z,   KC_X,    KC_C,    KC_V,           KC_NO,  KC_NO, KC_NO, KC_NO,  KC_RCTL,
                          LM(8,MOD_LGUI), KC_SPC, MO(7) ,         DF(0), KC_SPC,  KC_PSCR
    ),

    [7] = LAYOUT_split_3x5_3(
        KC_5,    KC_1,    KC_2,    KC_3,    KC_4,           KC_NO,  KC_NO, KC_UP,   KC_NO,  KC_TAB,
        KC_0,    KC_6,    KC_7,    KC_8,    KC_9,           KC_NO,  KC_LEFT, KC_DOWN, KC_RGHT,  KC_RSFT,
        KC_G,    KC_J,    KC_I,    KC_M,    KC_T,           KC_NO,  KC_NO, KC_NO, KC_NO,  KC_RCTL,
                          KC_ESC,  KC_ENT, _______,         _______, _______, _______
    ),

    [8] = LAYOUT_split_3x5_3(KC_Q, KC_1, KC_2, KC_3, KC_GRV, KC_K, LSFT_T(KC_1), LSFT(KC_2), LSFT(KC_3), KC_S, KC_A, KC_4, KC_5, KC_6, KC_H, KC_L, LSFT(KC_4), LSFT(KC_5), LSFT(KC_6), KC_F, KC_Z, KC_SPC, KC_C, LSFT(KC_E), KC_B, KC_J, KC_T, KC_M, LALT(KC_R), KC_D, KC_TRNS, KC_NO, KC_LGUI,KC_O, KC_LSFT, KC_RALT),


};

#if defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [0] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) } // Change these to your desired keycodes
};
#endif






