#include "action.h"
#include "action_layer.h"
#include "keymap_us.h"
#include "modifiers.h"
#include "quantum.h"
#include "quantum_keycodes.h"
#include QMK_KEYBOARD_H
#include "keycodes.h"

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case MO(7):
            if (record->event.pressed) {
                layer_on(7);  // or `layer_move(7)` if you want exclusive activation
            } else {
                layer_off(7);
                if (layer_state_is(1)) {
                    unregister_mods(MOD_BIT(KC_LGUI));
                }
            }
            return false;  // We handled it
    }
    return true;
}

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    // Layer 0: Base Layer
    [0] = LAYOUT_split_3x5_3(
        KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,           KC_Y,    KC_U,    KC_I,    KC_O,          KC_P,
        KC_A,    KC_S,    KC_D,    KC_F,    KC_G,           KC_H,    KC_J,    KC_K,    KC_L,          KC_TAB,
        KC_Z, KC_LCTL,    KC_C,    KC_V,    KC_B,           KC_N,    KC_M,    KC_QUOTE,KC_DOUBLE_QUOTE, KC_X,
        LM(3, MOD_LGUI), KC_SPACE,         MO(4),          LSFT_T(KC_ESC),  LT(1,KC_BSPC),   KC_LALT
        ),

    // Layer 2: Symbols/Nav Layer
    [1] = LAYOUT_split_3x5_3(
        KC_TILD, KC_EXLM, KC_AMPR, KC_HASH, KC_EQL,        KC_LBRC, KC_LCBR, KC_RCBR, KC_LPRN, KC_RPRN,
        KC_GRV,  KC_DLR,  KC_COMM, KC_DOT,  KC_COLN,       KC_LEFT, KC_DOWN, KC_UP,   KC_RIGHT, KC_PERC,
        KC_SCLN, KC_PIPE, KC_SLSH, KC_CIRC, KC_UNDS,       KC_RBRC, KC_MINS ,KC_BSLS, KC_AT,   KC_ASTR,
                          KC_LSFT,   KC_ENT,  MO(4),         KC_ENT,DF(0)   ,DF(2)
    ),
    // Layer 4: Gaming Base
    [2] = LAYOUT_split_3x5_3(
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,          KC_NO,   KC_NO,   KC_UP,   KC_NO,   KC_TAB,
        KC_LSFT, KC_A,    KC_S,    KC_D,    KC_F,          KC_NO,   KC_LEFT, KC_DOWN, KC_RGHT, KC_RSFT,
        KC_LCTL, KC_Z,    KC_X,    KC_C,    KC_V,          KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_RCTL,
                          LM(3, MOD_LGUI), KC_SPC, MO(5),    DF(0),   KC_SPC,  MO(10)
    ),
    // Layer 1: Compositor+general layer
    [3] = LAYOUT_split_3x5_3(
        KC_Q,    KC_1,    KC_2,    KC_3,        KC_GRV,         KC_K,    KC_O,    KC_P,    KC_W,        KC_S,
        KC_A,    KC_4,    KC_5,    KC_6,        KC_LEFT,        KC_LEFT, KC_DOWN, KC_UP,   KC_RIGHT,    KC_F,
        KC_Z,    KC_SPC,  KC_C,    LSFT(KC_E),  KC_B,           KC_I,    KC_T,    KC_M,    LALT(KC_R),  KC_D,
                          KC_TRNS,     KC_LCTL,   KC_LALT,      MO(7), KC_LSFT , KC_RALT
    ),


    // Layer 3: Function Keys and Numpad
    [4] = LAYOUT_split_3x5_3(
        KC_PAST, KC_1,    KC_2,    KC_3,    KC_0,          KC_WH_U, KC_F1,   KC_F2,   KC_F3,   KC_F11,
        KC_PSLS, KC_4,    KC_5,    KC_6,    KC_PPLS,       KC_F10,  KC_F4,   KC_F5,   KC_F6,   KC_END,
        KC_EQL, KC_7,    KC_8,    KC_9,    KC_MINS,       KC_WH_D, KC_F7,   KC_F8,   KC_F9,   KC_EQL,
                          KC_LCTL,   KC_LALT, KC_LSFT,       KC_TRNS, KC_ENT,  KC_F12
    ),


    // Layer 5: Gaming Numbers/Arrows
    [5] = LAYOUT_split_3x5_3(
        KC_5,    KC_1,    KC_W,    KC_3,    KC_4,          KC_NO,   KC_NO,   KC_UP,   KC_NO,   KC_TAB,
        KC_0,    KC_6,    KC_7,    KC_8,    KC_9,          KC_NO,   KC_LEFT, KC_DOWN, KC_RGHT, KC_RSFT,
        KC_G,    KC_J,    KC_I,    KC_M,    KC_T,          KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_RCTL,
                          KC_ESC,    KC_NO,   _______,       _______, _______, _______
    ),

    [6] = LAYOUT_split_3x5_3(
        KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,           KC_Y,    KC_U,    KC_I,    KC_O,            KC_P,
         LCTL_T(KC_A),    LSFT_T(KC_S),    KC_D,     KC_F,   KC_G,           KC_H,    KC_J,    KC_K,    LSFT_T(KC_L),            LCTL_T(KC_TAB),
        KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,           KC_N,    KC_M,    KC_DOUBLE_QUOTE, KC_QUOT, KC_LALT,
        LM(3, MOD_LGUI),KC_LSFT , LCTL_T(KC_ESC),           MO(4),   KC_LSFT  ,KC_SPACE),

[7] = LAYOUT_split_3x5_3(
    // Left Hand                                            // Right Hand
    KC_NO,     KC_NO,       KC_NO,        KC_NO,         KC_NO,            KC_WH_U,  LCTL(KC_PGUP),  LCTL(KC_PGDN), LCTL(KC_T),  KC_NO,
    KC_NO,     KC_NO,       KC_BTN4,      KC_BTN5,       KC_NO,            KC_WH_D,  KC_NO,          KC_NO,         KC_NO,       LCTL(KC_W),
    KC_NO,     KC_NO,       KC_NO,        KC_NO,         KC_NO,            KC_BTN1,  KC_BTN2,        KC_NO,         KC_NO,       KC_NO,
                            _______,      _______,       _______,          _______,   _______,      _______
),


};
#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
